name: meu_assistant
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  get: ^4.6.6
  animated_toggle_switch: ^0.8.3
  shared_preferences: ^2.3.2
  sqflite: ^2.3.3+2
  path: ^1.9.0
  intl: ^0.19.0
  country_flags: ^3.0.0
  flutter_map: ^7.0.2
  flutter_map_marker_popup: ^7.0.0
  latlong2: ^0.9.1
  google_maps_flutter: ^2.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/map_style.json
